spring.application.name=DailyBriefBotAPI

telegram.bot.token = ${BOT_TOKEN}
telegram.chat.id = ${TELEGRAM_ID}


news.rss.chennai=https://www.thehindu.com/news/cities/chennai/feeder/default.rss
news.rss.tamilnadu=https://www.thehindu.com/news/national/tamil-nadu/feeder/default.rss
news.rss.india=https://www.thehindu.com/news/national/feeder/default.rss
news.rss.world=https://feeds.bbci.co.uk/news/world/rss.xml

telegram.url = https://api.telegram.org/bot

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never