name: Daily_Brief

on:
  schedule:
  - cron: '30 0 * * *'   #6.00 AM IST every day, every month
  workflow_dispatch:
jobs:
  send-brief:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print trigger
      run: |
        echo "Triggered by : ${{ github.event_name}}"      
      
    - name: Call Daily Brief API
      run: |
        curl --fail --silent --show-error "${{ secrets.RENDER_DAILY_BRIEF_API_URL }}"
