name: Daily_Brief

on:
  schedule:
  - cron: '30 0 * * *'   #6.00 AM IST every day, every month
  workflow_dispatch:
jobs:
  send-brief:
    runs-on: ubuntu-latest
    
    steps:
    - name: Call Daily Brief API
      run: |
        curl --fail --silent --show-error \
          "https://dailybriefbotapi.onrender.com/api/dailyBrief/today"
